### ISSUE TITLE
EMF files from devEMF 4.4-2 look different from those produced by 4.1.-2

### ISSUE THREAD

**Issue by balthasars** [plfjohnson/devEMF#6] opened 2024-02-19 12:34 UTC
Hi there and thank you for your work on this package!

We've recently started testing a newer version of devEMF and have noticed that the plots saved with devEMF in 4.1-2 look different from the ones generated with version 4.4-2. 

- both when specifying and not specifying the height and the width of the EMF to be plotted, the resulting image size is 1px smaller on 4.4-2 than the image written to disk by 4.1.-2
- the chart appears to be shifted both vertically and horizontally

Here's a screenshot showing the differences in WinMerge (2.emf is generated from 4.4-2):

![image](https://github.com/plfjohnson/devEMF/assets/37873951/b899cb3d-c228-4976-8b57-a995507dde9f)

Here's the code used to generate a reproducible example:

``` r
generate_emf_plot <- function(dir, version){

  temp_path <- paste0(dir, "\\", version, ".emf")

  devEMF::emf(
    file = temp_path,
    emfPlus = TRUE,
    emfPlusFont = TRUE,
    height = 30,
    width = 30,
    units = "cm"
  )
  p <- plot(mtcars)
  dev.off()
  return(p)
}

# shared temporary dir
temp_dir_path <- here::here()
pak::cache_clean()

version <- 1
pak::pkg_install("devEMF@4.1-2", upgrade = FALSE)
#> ℹ Loading metadata database✔ Loading metadata database ... done
#>  
#> → Will install 1 package.
#> → Will download 1 package with unknown size.
#> + devEMF   4.1-2 [bld][cmp][dl]
#> ℹ Getting 1 pkg with unknown size
#> ✔ Got devEMF 4.1-2 (source) (213.27 kB)
#> ℹ Building devEMF 4.1-2
#> ✔ Built devEMF 4.1-2 (11.6s)
#> ✔ Installed devEMF 4.1-2  (106ms)
#> ✔ 1 pkg: added 1, dld 1 (213.27 kB) [18.7s]
p1 <- generate_emf_plot(dir = temp_dir_path, version = version)
pak:::unload("devEMF")
#>   Unloading devEMF...
pak::pkg_remove("devEMF")

version <- 2
pak::pkg_install("devEMF@4.4-2", ask = FALSE, upgrade = FALSE)
#>  
#> → Will install 1 package.
#> → Will download 1 CRAN package (542.53 kB).
#> + devEMF   4.4-2 [dl] (542.53 kB)
#> ℹ Getting 1 pkg (542.53 kB)
#> ✔ Got devEMF 4.4-2 (x86_64-w64-mingw32) (542.53 kB)
#> ✔ Installed devEMF 4.4-2  (108ms)
#> ✔ 1 pkg: added 1, dld 1 (542.53 kB) [842ms]
p2 <- generate_emf_plot(dir = temp_dir_path, version = version)
pak::pkg_remove("devEMF")
pak:::unload("devEMF")
#>   Unloading devEMF...
```

<sup>Created on 2024-02-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I've attached the two charts as a ZIP as Github doesn't support EMF files.
[devEMF-charts.zip](https://github.com/plfjohnson/devEMF/files/14331091/devEMF-charts.zip)

Do you have any suggestions on how one might work around this issue?
And would you consider this to be a bug or is this intended behavior?

Thanks so much in advance for having a look!

**Comment by plfjohnson** [comment] 2024-02-19 22:44
As far as I can tell, the EMF spec does not specify how viewing programs should handle rounding between logical coordinates and device coordinates, which led to the issue raised in #3.  You're seeing the effects of changes I implemented to address this issue.

In your example, both EMF files have headers that specify logical coordinates of 3543x3543 and physical coordinates of 299974 x 299974 micrometers.  However every viewing program I've tested seems to ignore the EMF micrometer specification and instead only pay attention to a separate entry in the EMF header that specifies physical coordinates in units of mm.   The older version of devEMF truncated the micrometers to give mm dimensions of 299 x 299 mm.  The newer version of devEMF rounds the micrometers to give mm dimensions of 300 x 300 mm.

You could tweak the requested physical dimensions in your R code to make truncation and rounding give the same result; see also comment https://github.com/plfjohnson/devEMF/issues/3#issuecomment-1587522960.

**Comment by plfjohnson** [comment] 2024-02-23 15:54
Just to close the loop here: I consider the current behavior to be the intended behavior so am closing this issue.

Fine-grained control over dimensions can be had through the `emf` function arguments of `width`, `height`, and `coordDPI` if taking into account that devEMF rounds and that most viewing programs use integer units of mm.

**Closed as completed by plfjohnson** 2024-02-23 15:54 UTC

**Comment by balthasars** [comment] 2024-02-23 16:59
Apologies for my very late reply and thank you very much for your detailed and helpful explanations of the changes with which we'll be able to fix our issues.

Best and have a great weekend,
Balthasar
